namespace: empovit
name: assisted_openshift
version: 2.0.0-pre-release
readme: README.md
authors:
- https://github.com/empovit
description: Collection of Ansible roles for OpenShift Assisted Installer
license:
- Apache-2.0
tags: [ openshift, aicli ]

dependencies:
   karmab.aicli: "*"


repository: https://github.com/empovit/ansible-assisted-openshift
issues: https://github.com/empovit/ansible-assisted-openshift/issues
build_ignore: []

