namespace: empovit
name: assisted_openshift
version: 1.0.0
readme: README.md
authors:
- https://github.com/empovit
description: Collection of Ansible roles for OpenShift Assisted Installer
license:
- Apache-2.0
tags: [ openshift ]

dependencies:
   git+/home/vit/work/ansible-aicli-modules/: make-collection


repository: https://github.com/empovit/ansible-assisted-openshift
issues: https://github.com/empovit/ansible-assisted-openshift/issues
build_ignore: []

